name: bach1-nsclc-analysis
channels:
  - conda-forge
dependencies:
  - python=3.11.5
  - pip
  - pip:
      - anndata==0.12.18
      - gseapy==1.2.1
      - h5py==3.16.0
      - harmonypy==0.0.10
      - igraph==1.0.0
      - infercnvpy==0.6.1
      - leidenalg==0.11.0
      - matplotlib==3.10.8
      - numpy==1.26.4
      - openpyxl==3.1.5
      - pandas==2.3.3
      - pillow==12.2.0
      - pyarrow==24.0.0
      - requests==2.34.2
      - scanpy==1.11.5
      - scikit-learn==1.8.0
      - scipy==1.17.1
      - seaborn==0.13.2
      - squidpy==1.8.2
      - statsmodels==0.14.6
